language: python
sudo: true # Needed for imagemagick
python:
  - "2.7"
  - "3.4"
  - "3.5"
#  - "pypy"

env:
  - RL=30
  - RL=31
  - RL=32

matrix:
  fast_finish: true

install:
  - sudo apt-get update # Needed for imagemagick
  - sudo apt-get install -y imagemagick libmagickcore-dev # Needed for imagemagick
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-rl${RL}
  - pip install tox coveralls Sphinx sphinx-rtd-theme

script: tox -e $TOX_ENV
after_success: coveralls $COVERALLS_OPTION

notifications:
  irc: "chat.freenode.net#xhtml2pdf"

before_script:
  - cd doc/source ; sphinx-build -nW -b html -d _build/doctrees . _build/html ; cd ../..
